const MAIN_NAVIGATOR = 'MainNavigator';

const HOME_STACK = 'HomeStack';
const CREATE_CARD = 'CreateCard';
const SEARCH_STACK = 'SearchStack';
const CONNECT_STACK = 'ConnectStack';
const PROFILE_STACK = 'ProfileStack';
const AUTH_STACK = 'AuthenStack';
const FAQ_SCREEN = 'Faq';
const TERM_OF_USER_SCREEN = 'TermOfUse';
const LAW_SCREEN = 'Law';
const PRIVACY_POLICY_SCREEN = 'PrivacyPolicy';

const AUTHEN = 'Authen';

const ENTER_PHONE_SCREEN_SIGNUP = 'EnterPhoneSignUp';
const ENTER_OTP_SCREEN_SIGNUP = 'EnterOtpSignUp';
const ENTER_INVITE_CODE_SIGNUP = 'EnterInviteCode';

const PROFILE_REGISTER_SCREEN = 'ProfileRegister';

const ENTER_PHONE_SCREEN_SIGNIN = 'EnterPhoneSignIn';
const ENTER_OTP_SCREEN_SIGNIN = 'EnterOtpSignIn';

const ENTER_OLD_PHONE_SCREEN = 'EnterOldPhone';
const ENTER_NEW_PHONE_SCREEN = 'EnterNewPhone';
const ENTER_NEW_OTP_SCREEN = 'EnterNewOtp';
const CREATE_PASSWORD_SCREEN = 'CREATE_PASSWORD_SCREEN';

const SPLASH_SCREEN = 'SPLASH_SCREEN';
const INVITE_FRIEND_SCREEN = 'INVITE_FRIEND_SCREEN';
const NOTICE_BOARD_SCREEN = 'NOTICE_BOARD_SCREEN';
const COMMENT_NOTICE_SCREEN = 'COMMENT_NOTICE_SCREEN';
const SELECT_ACQUAINTANCE_SCREEN = 'SELECT_ACQUAINTANCE_SCREEN';
const UPGRADE_ACCOUNT_SCREEN = 'UPGRADE_ACCOUNT_SCREEN';
const NETWORK_DISCONNECT_SCREEN = 'NETWORK_DISCONNECT_SCREEN';
const DELETE_ACOUNT_SCREEN = 'DELETE_ACOUNT_SCREEN';
const BOX_NOTIFICATION_SCREEN = 'BOX_NOTIFICATION_SCREEN'
const PUSH_NOTIFICATION_SCREEN = 'PUSH_NOTIFICATION_SCREEN'
const BOX_NOTIFICATION_DETAIL_SCREEN = 'BOX_NOTIFICATION_DETAIL_SCREEN'
export default {
  AUTHEN,
  ENTER_OTP_SCREEN_SIGNUP,
  ENTER_INVITE_CODE_SIGNUP,
  ENTER_PHONE_SCREEN_SIGNUP,
  PROFILE_REGISTER_SCREEN,

  ENTER_PHONE_SCREEN_SIGNIN,
  ENTER_OTP_SCREEN_SIGNIN,

  ENTER_OLD_PHONE_SCREEN,
  ENTER_NEW_PHONE_SCREEN,
  ENTER_NEW_OTP_SCREEN,

  HOME_STACK,
  CREATE_CARD,
  SEARCH_STACK,
  CONNECT_STACK,
  PROFILE_STACK,
  SPLASH_SCREEN,
  MAIN_NAVIGATOR,
  AUTH_STACK,
  FAQ_SCREEN,
  TERM_OF_USER_SCREEN,
  LAW_SCREEN,
  PRIVACY_POLICY_SCREEN,
  INVITE_FRIEND_SCREEN,
  NOTICE_BOARD_SCREEN,
  COMMENT_NOTICE_SCREEN,
  SELECT_ACQUAINTANCE_SCREEN,
  NETWORK_DISCONNECT_SCREEN,
  UPGRADE_ACCOUNT_SCREEN,
  CREATE_PASSWORD_SCREEN,
  DELETE_ACOUNT_SCREEN,
  BOX_NOTIFICATION_SCREEN,
  PUSH_NOTIFICATION_SCREEN,
  BOX_NOTIFICATION_DETAIL_SCREEN
};
