// notice board 
export const GET_LIST_NOTICE_BOARD = 'GET_LIST_NOTICE_BOARD';
export const GET_LIST_NOTICE_BOARD_SUCCESS = 'GET_LIST_NOTICE_BOARD_SUCCESS'
export const GET_LIST_NOTICE_BOARD_FAILED = 'GET_LIST_NOTICE_BOARD_FAILED'
